// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} key
 * @param {string} value
 * @returns {Promise.<boolean>}
 */
export async function JS_SetCookie(key, value) {
	// BEGIN USER CODE
    try {
        // Set cookie expiration time (e.g., 1 day)
        const expirationDays = 1;
        const date = new Date();
        date.setTime(date.getTime() + (expirationDays * 24 * 60 * 60 * 1000));
        const expires = "expires=" + date.toUTCString();

        // Set the cookie
        document.cookie = `${key}=${value}; ${expires}; path=/`;

        // Return true if successful
        return true;
    } catch (error) {
        console.error("Error setting cookie:", error);
        return false;
    }
	// END USER CODE
}
